---
ID: "f57d109d-a82c-4534-bb4a-8fec7e2e812a"
Parent: "0b42dc05-5cf9-4dd5-9a3a-8bdf11be2b88"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/system/Settings/Buckets/Facets/Project
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200428T071154Z
